### ISSUE TITLE
how ?

### ISSUE THREAD

**Issue by yekayee** [oguzhankrcb/Twitter-Account-Creator#1]
can u tell me how to run this script?

**Comment by oguzhankrcb** [comment]
Hi, you must have visual studio and c# to run it, but probably it wont work because it was really old project, i share it for give an idea to who wants to make something like that.

**Comment by yekayee** [comment]
i really need twitter account creator, can u make it for me?

**Comment by yekayee** [comment]
for my work

**Comment by oguzhankrcb** [comment]
I was at university when i made this project but now i am working so i dont have enough time to fix it or re-make it.

**Comment by yekayee** [comment]
maybe if u can make this project without using selenium or pupetter i will pay u

**Comment by yekayee** [comment]
if u want, u can send me message on telegram t.me/kikybulin

**Comment by oguzhankrcb** [comment]
Thank you for your interest but i really dont have enough time to do that...
